process FAS_ANNOTATION {
    queue 'all'
    executor 'slurm'
    cpus '16'

    input:
        path anno_tools         // Path: Path to annotation tools file
        path spice_library_dir   // Path: Library generated by spice_library.py



    output:
        path "${spice_library_dir}", emit: annotated_library_ch // Declare the generated directory as output




    script:
    """

    # Replace annoTools.txt in spice_library_dir with the one from anno_tools
    cp "${anno_tools}/annoTools.txt" "${spice_library_dir}/fas_data/annoTools.txt"


    # run the annotaion
    source "${anno_tools}/fas.profile"

    fas.doAnno \
        -i "${spice_library_dir}/transcript_data/transcript_set.fasta" \
        -o "${spice_library_dir}/fas_data/" \
        -t "${anno_tools}" \
        -n annotations \
        --cpus ${task.cpus} \

    """
}
