lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - .github/workflows/branch.yml
    - .github/workflows/ci.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - .github/workflows/branch.yml
    - .github/workflows/ci.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - assets/multiqc_config.yml
    - assets/email_template.html
    - assets/sendmail_template.txt
    - assets/email_template.txt
    - CODE_OF_CONDUCT.md
    - assets/nf-core-spice-nf_logo_light.png
    - docs/images/nf-core-spice-nf_logo_light.png
    - docs/images/nf-core-spice-nf_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  files_unchanged:
    - .github/CONTRIBUTING.md
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - .github/CONTRIBUTING.md
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .prettierignore
    - .prettierignore
    - .prettierignore
    - CODE_OF_CONDUCT.md
    - assets/nf-core-spice-nf_logo_light.png
    - docs/images/nf-core-spice-nf_logo_light.png
    - docs/images/nf-core-spice-nf_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  multiqc_config: false
  nextflow_config:
    - manifest.name
    - manifest.homePage
    - validation.help.beforeText
    - validation.help.afterText
    - validation.summary.beforeText
    - validation.summary.afterText
  readme:
    - nextflow_badge
nf_core_version: 3.2.0
repository_type: pipeline
template:
  author: Felix Haidle
  description: Nextflow pipeline to create SPICE libraries
  force: false
  is_nfcore: false
  name: spice_library_pipeline
  org: BIONF
  outdir: .
  skip_features:
    - igenomes
    - gitpod
    - codespaces
    - multiqc
    - fastqc
    - seqera_platform
    - slackreport
    - adaptivecard
    - email
    - github_badges
    - ci
  version: 1.0.0dev
