bump_version: null
lint:
  files_exist:
  - conf/igenomes.config
  - conf/igenomes_ignored.config
  - assets/multiqc_config.yml
  - conf/igenomes.config
  - conf/igenomes_ignored.config
  - assets/multiqc_config.yml
  - CODE_OF_CONDUCT.md
  - assets/nf-core-spice-nf_logo_light.png
  - docs/images/nf-core-spice-nf_logo_light.png
  - docs/images/nf-core-spice-nf_logo_dark.png
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml
  files_unchanged:
  - .github/CONTRIBUTING.md
  - .github/CONTRIBUTING.md
  - assets/sendmail_template.txt
  - .github/CONTRIBUTING.md
  - .github/CONTRIBUTING.md
  - assets/sendmail_template.txt
  - CODE_OF_CONDUCT.md
  - assets/nf-core-spice-nf_logo_light.png
  - docs/images/nf-core-spice-nf_logo_light.png
  - docs/images/nf-core-spice-nf_logo_dark.png
  - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config: false
  nextflow_config:
  - manifest.name
  - manifest.homePage
  - validation.help.beforeText
  - validation.help.afterText
  - validation.summary.beforeText
  - validation.summary.afterText
nf_core_version: 3.2.0
org_path: null
repository_type: pipeline
template:
  author: "Felix Haidle"
  description: Nextflow pipeline to create SPICE libraries
  force: true
  is_nfcore: false
  name: spice-nf
  org: BIONF
  outdir: .
  skip_features:
  - igenomes
  - gitpod
  - codespaces
  - multiqc
  - fastqc
  - seqera_platform
  - slackreport
  - adaptivecard
  - email
  - github_badges
  - ci
  version: 1.0.0dev
update: null
