name: spice_env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - pandas
  - scipy
  - matplotlib
  - tqdm
  - yaml
  - requests
  - plotly
  - pyranges
  - gzip  
  - pip
  - pip:
      - greedyFAS
