name: spice_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.7
  - numpy
  - pandas
  - scipy
  - matplotlib
  - tqdm
  - pyyaml
  - requests
  - plotly
  - pyranges
  - pip
  - pip:
    - greedyFAS
