name: spice_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7  
  - greedyFAS
  - pyranges
  - requests
  - jsonschema  
  - argparse
  - itertools
  - plotly
  - pathlib
  - tqdm
  - numpy
  - matplotlib
  - scipy
  - pyyaml  
  - pandas
  - gzip
  - shutil
